### ISSUE TITLE
Issue with 2.0.6

### ISSUE THREAD

**Issue by HeresJonny** [MrSprigster/script.module.python.twitch#63]
KodiSetup-20190308-386045c3-master-x64.exe
python-twitch for Kodi 2.0.6

2019-03-09 23:27:52.471 T:6796 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |TBD|

**Comment by anxdpanic** [comment]
This is not an issue, this is intentional warning for developers, and v5 is not scheduled for removal at this stage. This does not affect usage at all.
